apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mi-app-prueba
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/florencia-nu/mi-app-prueba.git
    targetRevision: HEAD
    path: desarrollador
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
